config/routes.rb
Rails.application.routes.draw do
  get 'accounts' => 'accounts#edit'
  patch "accounts" => 'accounts#update'
  put "account"=> 'accounts#update'

   # Webhook routes
  get "webhooks/uninstall"
  post "webhooks/uninstall"

  get "sessions/new"
  post "sessions/create"
  get "sessions/destroy"

  resources :products do
    collection do
      get 'import'
    end
    resources :variants
  end

  resources :orders do
    collection do
      get 'import'
    end
  end

  resources :contests

  # Dashboard routes
  get "dashboard/index"
  post "create_contest" => 'dashboard#create_contest'
  get "test_connection" => 'dashboard#test_connection'

  # Shopify routes
  get 'shopify/authorize' => 'shopify#authorize'
  post 'shopify/authorize' => 'shopify#authorize'

  get 'shopify/install' => 'shopify#install'
  post 'shopify/install' => 'shopify#install'


  # You can have the root of your site routed with "root"
  root 'dashboard#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    # Load past results in reverse order
    @contests = Contest.order("created_at desc")

    # Instantiate a new Contest so the form loads properly
    @contest = Contest.new

    # Load the Products we want to use for Contests
    @products = Product.all.order(:name)
    logger.debug "products #{@products}"
  end


  # This method creates a Contest and returns the winner(s) in the
  # notice message
  def create_contest
    @contest = Contest.new(contest_params)
# Store the name of the product for easier readability
    @contest.product_name = Product.find_by_shopify_product_id(contest_params[:product_id]).try(:name) if contest_params[:product_id].present?
    logger.debug "contest params :#{@contest.product_name}"
    
    respond_to do |format|
      if @contest.save
        # Pick a winner
        candidates = Order.candidate_list(params)
        contest_results = ContestResults.new(candidates)

        # Save the winner        
        @contest.update_attribute(:order_id, contest_results.results)

        format.html { redirect_to root_path, notice: "Contest Winner: <a href='#{order_path(@contest.order)}'>#{@contest.order.email}</a>" }
        format.json { render action: 'show', status: :created, location: @contest }

      else
        format.html { redirect_to root_path, alert: "Unable to create a Contest #{@contest.errors.full_messages.to_s}" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end

  end

  private

  def contest_params
    params.require(:contest).permit(:name, :product_id, :start_date, :end_date, :max_results, :order_id, :criteria)
  end


end

app/helpers/dash_board_helper.rb
module DashBoardHelper
end

app/views/dashboard/index.html.erb
<%- model_class = Contest -%>
<%- content_for :sidebar do -%>
<h4><%= t('dashboard.sidebar.title') %></h4>
<% if current_account.can_create_contests? %>
<p><%= t('dashboard.sidebar.content') %></p>
<%= form_for @contest, :url => create_contest_path do |f| %>
<div class="control-group">
  <%= f.label :name, "Contest Name *"  %>
  <div class="controls">
    <%= f.text_field :name, :class => 'text_field', :required => true %>
  </div>
</div>
<div class="control-group">
  <%= f.label :product_id, "Type *" %>
  <div class="controls">
    <select id="contest_product_id" name="contest[product_id]" required="required">
      <option>Any Product</option>
      <optgroup label="Specific Product">
        <%- @products.each do |product| -%>
        <option value="<%= product.id %>"><%= product.name %></option>
        <%- end -%>
      </optgroup>
    </select>
  </div>
</div>
<div class="control-group">
  <%= f.label :start_date, "Order Date Range (optional)" %>
  <div class="controls">
    <%= f.text_field :start_date, :class => 'text_field' %>
    <%= f.text_field :end_date, :class => 'text_field' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :max_results, "Max # (optional)" %>
  <div class="controls">
    <%= f.text_field :max_results, :class => 'text_field' %>
  </div>
</div>
<div class="form-actions">
  <input type="submit" value="Submit" class="btn"/>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
  root_path, :class => 'btn' %>
</div>
<!-- End form -->
<%- end -%>
<% else %>
<p> Uh oh!  Looks like you've used up your monthly allotment of Contests!  If you need more, <%= link_to "Click here to upgrade your account", account_path %>.
<% end %>
<p>Having trouble?  <a href="<%= test_connection_path %>">Click here to test your connection to Shopify</a>.</p>
<!-- End sidebar -->
<%- end -%>
<h1>Contests</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Criteria</th>
      <th>Winner</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <% @contests.each do |contest| %>
    <tr>
      <td><%= contest.name %></td>
      <td><%= contest.criteria %></td>
      <% if contest.order.present? %>
      <td>Order <%= link_to contest.order.number, order_path(contest.order) %>, <%= contest.order.first_name %> <%= contest.order.last_name %> (<%= mail_to contest.order.email, contest.order.email %>)</td>
      <% else %>
      <td>Error picking winner</td>
      <% end %>
      <td><%=l contest.created_at, format: :long %></td>
    </tr>
    <% end %>
  </tbody>
</table>