config/routes.rb
Rails.application.routes.draw do
  get 'accounts' => 'accounts#edit'
  patch "accounts" => 'accounts#update'
  put "account"=> 'accounts#update'

   # Webhook routes
  get "webhooks/uninstall"
  post "webhooks/uninstall"

  get "sessions/new"
  post "sessions/create"
  get "sessions/destroy"

  resources :products do
    collection do
      get 'import'
    end
    resources :variants
  end

  resources :orders do
    collection do
      get 'import'
    end
  end

  resources :contests

  # Dashboard routes
  get "dashboard/index"
  post "create_contest" => 'dashboard#create_contest'
  get "test_connection" => 'dashboard#test_connection'

  # Shopify routes
  get 'shopify/authorize' => 'shopify#authorize'
  post 'shopify/authorize' => 'shopify#authorize'

  get 'shopify/install' => 'shopify#install'
  post 'shopify/install' => 'shopify#install'


  # You can have the root of your site routed with "root"
  root 'dashboard#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Contestapp" %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
         <% if logged_in? %>
             <a class="btn btn-navbar" data-target=".nav-collapse"
   data-toggle="collapse">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
             </a>
             <% end %>
             <a class="brand" href="/">Contest App</a>
             <% if logged_in? %>
               <div class="container-fluid nav-collapse">
                 <ul class="nav">
                   <li><%= link_to "Products", products_path  %></li>
                   <li><%= link_to "Orders", orders_path  %></li>
                   <li><%= link_to "My Accounts", accounts_path  %></li>
                   <li><%= link_to "Logout", sessions_destroy_path %>
                   </li>
                 </ul>
               </div><!--/.nav-collapse -->
             <% end %>
          </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
          <% if content_for?(:sidebar) %>
          <div class="span3">
            <div class="well sidebar-nav">
              <%= yield(:sidebar) %>
            </div>
          </div>
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <% else %>
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <% end %>
        </div>
        <footer>
          <p>&copy; Company 2014</p>
          <a href="http://www.miibeian.gov.cn" target="_blank">沪ICP备16015983号-1</a>
        </footer>
        </div> <!-- /container -->
  </body>
</html>